config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'

  resources :posts
  resources :authors
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :posts, dependent: :destroy
  validates :name, :position, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author
  validates :author_id, :title, :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
  end

  def create
    @author = Author.new(author_params)

    if @author.valid? && @author.save
      redirect_to author_path(@author)
    else
      render :new
    end
  end

  def new
    @author = Author.new
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])

    if @author.update(author_params)
      redirect_to author_path(@author)
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id])
    if @author.destroy
      redirect_to authors_path
    else
      render :edit
    end
  end

  private

  def author_params
    params.require(:author).permit(
      :name,
      :position
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all
  end

  def show
    @post = Post.where(id: params[:id]).first

    if @post
      # nothing as we've found the post
    else
      # handle not finding post based on application logic
      flash[:error] = "I'm sorry but the post you are looking for was lost in the ether"
      redirect_to posts_path
    end
  end

  def create
    @post = Post.new(post_params)

    if @post.valid? && @post.save
      redirect_to post_path(@post)
    else
      render :new
    end
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.destroy
      redirect_to posts_path
    else
      render :edit
    end
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :author_id,
      :body
    )
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/layout_helper.rb
module LayoutHelper
  def javascript_controller
    controller_path.gsub('/', '_').camelize
  end

  def javascript_action
    controller.action_name.camelize(:lower) + 'Action'
  end
end

app/helpers/site_controller_helper.rb
module SiteControllerHelper
end

app/views/authors/_form.html.haml
= form_for @author, html: {class: "nifty_form"} do |f|
  - if @author.errors.any?
    %div
      Something Went Wrong
    %ul
      - @author.errors.full_messages.each do |e|
        %li
          = e
  %div.container
    %div.form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'
    %div.form-group
      = f.label :position
      = f.text_field :position, class: 'form-control'
    %div
      = f.submit f.object.persisted? ? 'Update' : 'Create', class: 'btn btn-primary'

app/views/authors/edit.html.haml
%div.container
  %h2.mt-4.mb-4
    Edit Author
= render partial: "form"

app/views/authors/index.html.haml
%div.container
  %h2.h2
    Author List
  %ul.list-group
    - @authors.each do |author|
      %li.list-group-item
        = link_to "#{author.name}", author_path(author)
%div.container
  = image_tag("dir/screen")

app/views/authors/new.html.haml
%div.container
  %h2.mt-4.mb-4
    New Author
= render partial: "form"

app/views/authors/show.html.haml
%div.container
  %h2
    =@author.name

  %p
    =@author.position

  %p
    ="Author Since: #{@author.created_at}"
  %ul
    - @author.posts.each  do |post|
      %li
        =link_to post.title, post_path(post)
%div.container
  = link_to 'Delete Author', author_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-danger'
  = link_to "Edit Author", edit_author_path(@author), class: 'btn btn-default btn-primary'
  = link_to "Return to index", authors_path, class: 'btn btn-default btn-info'

app/views/layouts/application.html.haml
!!!

%html
  %head
    %title
      Blog

    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

%body.d-flex.flex-column.h-100{data: {controller: javascript_controller, action: javascript_action}}
  %header
    %nav.navbar.navbar-expand-md.navbar-dark.bg-dark
      %a.navbar-brand{href: "#"}
        Fixed navbar
        %button.navbar-toggler{type: "button", data: {toggle: "collapse", target: "#navbarCollapse"}, aria: {controls: "navbarCollapse", expanded: "false", label: "Toggle navigation"}}
          %span.navbar-toggler-icon
            %div.collapse.navbar-collapse#navbarCollapse
              %ul.navbar-nav.mr-auto
                %li.nav-item.active
                  %a.nav-link{href: "#"}
                    Home
                    %span.sr-only
                      (current)
                %li.nav-item
                  %a.nav-link{href: "#"}
                    Link
                %li.nav-item
                  %a.nav-link.disabled{href: "#", tabindex: "-1", aria: {disabled: "true"}}
                    Disabled
              %form.form-inline.mt-2.mt-md-0
                %input.form-control.mr-sm-2{type: "text", placeholder: "Search", aria: {label: "Search"}}
                  %button.btn.btn-outline-success.my-2.my-sm-0{type: "submit"}
                    Search

  = yield

app/views/posts/_form.html.haml
= form_for @post, html: {class: "nifty_form"} do |f|
  - if @post.errors.any?
    %div
      Something Went Wrong
    %ul
      - @post.errors.full_messages.each do |e|
        %li
          = e
  %div.container
    %div.form-group
      = f.label :title
      = f.text_field :title, class: 'form-control'
    %div.form-group
      = f.label :body
      = f.text_area :body, size: "60x12", class: 'form-control'
    %div.form-group
      = f.label :author
      = f.select :author_id, options_from_collection_for_select(Author.all, :id, :name), {}, { :class => 'form-control'}
    %div
      = f.submit f.object.persisted? ? 'Update' : 'Create', class: 'btn btn-primary'

app/views/posts/edit.html.haml
%div.container
  %h2.mt-4.mb-4
    Edit Post
= render partial: "form"

app/views/posts/index.html.haml
%div.container
  %table.table
    %thead
      %tr
        %th
          Blog Title
        %th
        %th
        %th
    %tbody
      - @posts.each do |post|
        %tr
          %td
            = link_to "#{post.title}", post_path(post)
          %td
            = link_to 'Delete Post', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-danger'
          %td
            = link_to "Edit Post", edit_post_path(post), class: 'btn btn-default btn-primary'
%div.container
  = link_to "New Post", new_post_path, class: 'btn btn-default btn-primary'
  = link_to "New Author", new_author_path, class: 'btn btn-default btn-info'

app/views/posts/new.html.haml
%h2 New Post
= render partial: "form"

app/views/posts/show.html.haml
%div.container
  %h2.mt-4.mb-2
    =@post.title
  %h4
    Written by:
    =link_to @post.author.name, author_path(@post.author)

  %p
    =@post.body

  %p
    ="Created #{@post.created_at}"

  = link_to 'Delete Post', post_path, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-default btn-danger'
  = link_to "Edit Post", edit_post_path(@post), class: 'btn btn-default btn-primary'
  = link_to "Return to index", posts_path, class: 'btn btn-default btn-info'

app/views/site/index.html.haml
site index